version: '3.7'
services:
    jenkins-dodcker:
        image: docker:18.09-dind
        privileged: true
        user: root
        ports:
             - 2375:2375
        container_name: jenkins-docker
        volumes:
            - /opt/jenkins/jenkins-data:/var/jenkins_home
          #  - /opt/jenkins/jenkins-docker-certs:/certs/client:ro
        networks: 
            jenkins:
                aliases:
                    - docker
    jenkins:
        image: jenkinsci/blueocean
        environment:
            - DOCKER_HOST=tcp://docker:2375
        privileged: true
        user: root
        ports:
            - 8080:8080
            - 50000:50000
        container_name: jenkins
        volumes:
            - /opt/jenkins/jenkins-data:/var/jenkins_home
         #   - /opt/jenkins/jenkins-docker-certs:/certs/client:ro
        networks: 
            - jenkins
networks:
    jenkins:

